import type { Inputs, Result, ToolSlug } from '../types';
import { dreamSymbols, identities } from '../data/content';
import { tarotDeck } from '../data/tarotDeck';
export function reduceNumber(n: number): number { while(n>9 && ![11,22,33].includes(n)) n=String(n).split('').reduce((s,c)=>s+Number(c),0); return n; }
export function validDate(date: string): boolean { const d=new Date(date+'T12:00:00'); return /^\d{4}-\d{2}-\d{2}$/.test(date)&&!isNaN(+d)&&d.getFullYear()>=1900&&d.getFullYear()<=new Date().getFullYear()&&d.getFullYear()===Number(date.slice(0,4))&&d.getMonth()+1===Number(date.slice(5,7))&&d.getDate()===Number(date.slice(8,10))&&date<=localToday(); }
export function localToday(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function numerology(name:string,date:string){const letters=name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toUpperCase().replace(/[^A-Z]/g,'');const sum=(s:string)=>[...s].reduce((n,c)=>n+(c.charCodeAt(0)-65)%9+1,0);return {life:reduceNumber([...date.replaceAll('-','')].reduce((s,c)=>s+Number(c),0)),expression:reduceNumber(sum(letters)),soul:reduceNumber(sum(letters.replace(/[^AEIOU]/g,'')))};}
export function score(answers:number[],count:number){const values=Array.from({length:count},(_,index)=>({index,score:answers.filter(x=>x===index).length}));return values.sort((a,b)=>b.score-a.score||a.index-b.index);}
export function lunar(date:string,time='12:00'){const days=(+new Date(`${date}T${time}:00+07:00`)-Date.UTC(2000,0,6,18,14))/86400000;const age=((days%29.530588853)+29.530588853)%29.530588853;return {phase:Math.floor((age/29.530588853*8)+.5)%8,illumination:Math.round((1-Math.cos(age/29.530588853*2*Math.PI))/2*100),age};}
export function zodiac(date:string){const parts=new Intl.DateTimeFormat('en-u-ca-chinese',{year:'numeric',month:'numeric',day:'numeric',timeZone:'UTC'}).formatToParts(new Date(date+'T12:00:00Z'));const year=Number(parts.find(p=>(p.type as string)==='relatedYear')?.value);if(!year)throw new Error('Trình duyệt chưa hỗ trợ lịch Trung Hoa. Hãy thử phiên bản trình duyệt mới hơn.');return {year,animal:['Tý','Sửu','Dần','Mão','Thìn','Tỵ','Ngọ','Mùi','Thân','Dậu','Tuất','Hợi'][((year-4)%12+12)%12],element:['Mộc','Hỏa','Thổ','Kim','Thủy'][Math.floor((((year-4)%10)+10)%10/2)]};}
export function sunSign(date:string){const md=Number(date.slice(5,7))*100+Number(date.slice(8,10));const bounds=[120,219,321,420,521,622,723,823,923,1023,1122,1222];const names=['Ma Kết','Bảo Bình','Song Ngư','Bạch Dương','Kim Ngưu','Song Tử','Cự Giải','Sư Tử','Xử Nữ','Thiên Bình','Bọ Cạp','Nhân Mã','Ma Kết'];return names[bounds.findIndex(b=>md<b)===-1?12:bounds.findIndex(b=>md<b)];}
function randomInt(n:number){const v=new Uint32Array(1);const limit=Math.floor(4294967296/n)*n;do{crypto.getRandomValues(v);}while(v[0]>=limit);return v[0]%n;}
export function drawTarot(count:number){const pool=[...tarotDeck];return Array.from({length:count},()=>({...pool.splice(randomInt(pool.length),1)[0],reversed:randomInt(2)===1}));}
export function calculate(slug:ToolSlug,input:Inputs):Result{
 const base:Result={title:'',subtitle:'Một góc nhìn biểu tượng để suy ngẫm về chính mình.',symbol:'✦',traits:['Tự quan sát','Cởi mở','Phát triển'],details:'Mỗi truyền thống mang một cách nhìn khác nhau. Hãy giữ lại những điều đồng điệu với trải nghiệm thực tế của bạn.',strength:'Bạn có thể bắt đầu từ việc nhận ra một nguồn lực nhỏ mình đã có.',growth:'Dành chỗ cho những khía cạnh khác biệt; một biểu tượng không thể kể hết con người bạn.',reflection:'Điều gì trong góc nhìn này khiến bạn đồng điệu, và điều gì không?',facts:[]};
 if(slug==='numerology'){const n=numerology(input.name!,input.date!);const meanings:Record<number,string>={1:'Người mở lối',2:'Người kết nối',3:'Người biểu đạt',4:'Người xây nền',5:'Người khám phá',6:'Người nuôi dưỡng',7:'Người chiêm nghiệm',8:'Người kiến tạo',9:'Người sẻ chia',11:'Người truyền cảm hứng',22:'Người xây ước mơ',33:'Người dẫn dắt bằng yêu thương'};return {...base,title:`${n.life} · ${meanings[n.life]}`,symbol:String(n.life),subtitle:'Con số đường đời — một lăng kính nhỏ từ ngày bạn đến với thế giới.',facts:[{label:'Số đường đời',value:String(n.life)},{label:'Số biểu đạt',value:String(n.expression)},{label:'Số linh hồn',value:n.soul?String(n.soul):'Tên không có nguyên âm A/E/I/O/U'}],details:`Ngày sinh: ${input.date!.replaceAll('-',' + ')}. Cộng từng chữ số rồi rút gọn, giữ 11, 22, 33, cho kết quả ${n.life}. ${meanings[n.life]} gợi sự quan tâm đến ${n.life%2?'khám phá ý nghĩa, tự chủ và biểu đạt':'kết nối, chăm sóc và xây dựng nền tảng'}. Số biểu đạt và linh hồn dùng quy đổi chữ cái Pythagoras; đây là một quy ước biểu tượng.`,traits:identities.traits[n.life%8],reflection:'Bạn muốn chủ động nuôi dưỡng phẩm chất nào trong tuần này?'};}
 if(slug==='tarot'){const cards=drawTarot(input.spread==='3'?3:1);return {...base,title:cards.length===1?cards[0].name:'Ba lá bài · Một khoảng lặng',symbol:'☼',subtitle:'Lá bài không chọn thay bạn. Chúng mở thêm một cách đặt câu hỏi.',traits:cards.map(c=>c.theme),facts:cards.map((c,i)=>({label:cards.length===1?'Góc nhìn hôm nay':['Bối cảnh','Hiện tại','Gợi ý hành động'][i],value:`${c.name} · ${c.reversed?'Ngược':'Xuôi'}`})),details:cards.map(c=>`${c.name}: ${c.meaning} ${c.reversed?'Ở chiều ngược, hãy xem điều gì đang bị bỏ qua hoặc cần một nhịp chậm hơn.':'Ở chiều xuôi, hãy cân nhắc cách biểu tượng này đang hiện diện trong đời sống.'}`).join('\n\n'),reflection:`Với câu hỏi “${input.question}”, đâu là một bước nhỏ nằm trong khả năng lựa chọn của bạn?`};}
 if(['element-personality','spirit-animal','fantasy-archetype'].includes(slug)){const names=slug==='element-personality'?identities.elements:slug==='spirit-animal'?identities.animals:identities.fantasy;const ranks=score(input.answers!,names.length);const i=ranks[0].index;return {...base,title:names[i],symbol:['△','≈','◇','○','⌘','◈','⟡','☽'][i],traits:identities.traits[i],subtitle:`Bạn có thể cảm thấy đồng điệu với ${names[i]} — ${identities.traits[i].join(', ').toLowerCase()}.`,facts:[{label:'Biểu tượng chính',value:names[i]},{label:'Góc nhìn bổ sung',value:names[ranks[1].index]},{label:'Mức đồng điệu',value:`${ranks[0].score}/${input.answers!.length} lựa chọn`}],details:`Các lựa chọn của bạn nghiêng về ${identities.traits[i].join(', ').toLowerCase()}. ${names[ranks[1].index]} là một sắc thái bổ sung. ${ranks[0].score===ranks[1].score?'Có điểm bằng nhau; kết quả dùng thứ tự ưu tiên cố định được giải thích trong phương pháp. ':''}Đây là ảnh chụp những lựa chọn ở thời điểm hiện tại; bạn có thể thay đổi cùng trải nghiệm.`,strength:`Thử vận dụng sự ${identities.traits[i][0].toLowerCase()} để hỗ trợ một việc quan trọng với bạn.`,growth:`Khi quá nghiêng về ${names[i]}, hãy thử mượn góc nhìn ${names[ranks[1].index]} để cân bằng.`,reflection:slug==='fantasy-archetype'?'Nhiệm vụ nhỏ: chọn một việc tử tế hoặc can đảm, thực hiện trong 24 giờ và ghi lại điều bạn học được.':'Khi nào phẩm chất này giúp bạn, và khi nào bạn muốn thử một cách phản ứng khác?'};}
 if(slug==='lunar-profile'){const l=lunar(input.date!,input.time||'12:00');return {...base,title:['Trăng mới','Trăng lưỡi liềm đầu tháng','Trăng thượng huyền','Trăng khuyết dần đầy','Trăng tròn','Trăng khuyết dần vơi','Trăng hạ huyền','Trăng lưỡi liềm cuối tháng'][l.phase],symbol:'☽',subtitle:'Một nhịp trăng ngày sinh, một lời mời tìm nhịp sống của riêng bạn.',facts:[{label:'Độ chiếu sáng gần đúng',value:`${l.illumination}%`},{label:'Tuổi trăng ước tính',value:`${l.age.toFixed(1)} ngày`},{label:'Giờ quy ước',value:`${input.time||'12:00'} · UTC+7`}],details:'Kết quả gần đúng từ chu kỳ trung bình, không dùng lịch thiên văn thực đo. Biểu tượng trăng gợi một chu kỳ bắt đầu, lớn lên, tỏa sáng và nghỉ ngơi. Bạn không cần luôn ở cùng một nhịp.',reflection:'Lúc này bạn cần bắt đầu, nuôi dưỡng, chia sẻ hay nghỉ ngơi?'};}
 if(slug==='chinese-zodiac'){const z=zodiac(input.date!);return {...base,title:`${z.animal} · Hành ${z.element}`,symbol:'☼',facts:[{label:'Con giáp',value:z.animal},{label:'Ngũ hành năm sinh',value:z.element},{label:'Năm âm lịch',value:String(z.year)}],details:`Ngày sinh thuộc năm âm lịch ${z.year}, đã xét ranh giới Tết theo lịch Trung Hoa của trình duyệt. ${z.animal} và hành ${z.element} là các biểu tượng của chu kỳ truyền thống, không quyết định tính cách hay sự tương hợp giữa người với người.`,reflection:'Trong một chu kỳ mới, bạn muốn giữ điều gì và thay đổi điều gì?'};}
 if(slug==='birth-chart')return {...base,title:sunSign(input.date!),symbol:'☉',subtitle:'Cung Mặt Trời gần đúng · Hồ sơ bầu trời cơ bản',facts:[{label:'Mặt Trời · gần đúng',value:sunSign(input.date!)},{label:'Mặt Trăng & cung Mọc',value:'Chưa tính — cần lịch thiên văn'},{label:'Địa điểm bạn nhập',value:input.place!}],details:'Cung Mặt Trời được tra bằng ranh giới ngày cố định, có thể khác ở ngày chuyển cung. Giờ và địa điểm sinh được giữ làm bối cảnh, chưa được dùng để tính vị trí thiên thể. Không có độ số hành tinh hay cung Mọc giả định.',reflection:'Bạn nhận ra phẩm chất nào của mình qua những tình huống thực tế, thay vì chỉ từ một nhãn cung?'};
 const text=`${input.dream} ${input.symbols||''}`.toLocaleLowerCase('vi');const found=dreamSymbols.filter(s=>s.words.some(w=>text.includes(w)));return {...base,title:found.length?found.map(s=>s.name).join(' · '):'Một câu chuyện của riêng bạn',symbol:'☁',subtitle:'Lắng nghe liên tưởng của bạn, không áp đặt một lời giải duy nhất.',traits:found.length?found.map(s=>s.name):['Liên tưởng cá nhân','Lắng nghe','Ghi nhận'],facts:[{label:'Cảm xúc đi kèm',value:input.emotion||'Chưa gọi tên'},{label:'Nhóm biểu tượng',value:String(found.length)}],details:found.length?found.map(s=>s.meaning).join('\n\n'):'Từ điển chưa tìm thấy biểu tượng tương ứng. Hãy chọn hình ảnh bạn nhớ rõ nhất và viết ba liên tưởng cá nhân; ý nghĩa của bạn có thể khác bất kỳ từ điển nào.',reflection:`Khi cảm thấy ${input.emotion?.toLowerCase()||'như trong giấc mơ'}, hình ảnh nào khiến bạn liên tưởng đến đời sống gần đây?`};
}
