CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY,email TEXT NOT NULL DEFAULT '',name TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS readings (id TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,tool_slug TEXT NOT NULL,created_at TEXT NOT NULL,input_summary TEXT NOT NULL,result_json TEXT NOT NULL,saved INTEGER NOT NULL DEFAULT 0,added_to_profile INTEGER NOT NULL DEFAULT 0);
CREATE INDEX IF NOT EXISTS idx_readings_user_created ON readings(user_id, created_at DESC);
CREATE TABLE IF NOT EXISTS content (slug TEXT PRIMARY KEY,name TEXT NOT NULL,description TEXT NOT NULL,category TEXT NOT NULL,color TEXT NOT NULL,minutes INTEGER NOT NULL,input TEXT NOT NULL,method TEXT NOT NULL,updated_at TEXT NOT NULL);
