type D1Result<T=Record<string, unknown>>={results:T[]};
type D1Statement={bind:(...values:unknown[])=>D1Statement;first:<T=Record<string,unknown>>()=>Promise<T|null>;all:<T=Record<string,unknown>>()=>Promise<D1Result<T>>;run:()=>Promise<unknown>};
type D1Database={prepare:(sql:string)=>D1Statement;batch:(statements:D1Statement[])=>Promise<unknown>};
type Env={DB?:D1Database;ASSETS?:{fetch:(request:Request)=>Promise<Response>};ADMIN_USER_IDS?:string};
type User={id:string;email:string;name:string};
const defaults=[{slug:'numerology',name:'Thần số học',description:'Những con số kể một câu chuyện. Câu chuyện của bạn là gì?',category:'Ngày sinh & vũ trụ',color:'#B69CFF',minutes:2,input:'Họ tên & ngày sinh',method:'Cộng các chữ số của ngày sinh và quy đổi tên theo hệ Pythagoras.'},{slug:'tarot',name:'Tarot',description:'Một lá bài, một khoảng lặng, một góc nhìn bạn chưa từng nghĩ đến.',category:'Trực giác & biểu tượng',color:'#F2C66D',minutes:3,input:'Một câu hỏi',method:'Rút ngẫu nhiên từ bộ 78 lá bài, với trạng thái xuôi hoặc ngược.'},{slug:'lunar-profile',name:'Hồ sơ Mặt Trăng',description:'Tìm một nhịp điệu của riêng mình, dưới ánh trăng ngày bạn đến.',category:'Ngày sinh & vũ trụ',color:'#82DFFF',minutes:2,input:'Ngày sinh',method:'Ước tính tuổi trăng từ chu kỳ trung bình 29,530588853 ngày.'},{slug:'dream-interpretation',name:'Giải mã giấc mơ',description:'Lắng nghe những biểu tượng mà thế giới trong bạn để lại.',category:'Trực giác & biểu tượng',color:'#F39AB8',minutes:3,input:'Mô tả giấc mơ',method:'So khớp từ khóa với từ điển biểu tượng cục bộ.'},{slug:'birth-chart',name:'Bản đồ sao',description:'Một lời chào từ bầu trời, một góc nhìn về thế giới bên trong.',category:'Ngày sinh & vũ trụ',color:'#9DAEFF',minutes:3,input:'Ngày, giờ & nơi sinh',method:'Xác định cung Mặt Trời gần đúng theo ngày.'},{slug:'element-personality',name:'Tính cách nguyên tố',description:'Lửa, Nước, Đất hay Khí — điều gì nuôi dưỡng năng lượng của bạn?',category:'Tính cách & bản sắc',color:'#9FE4C2',minutes:3,input:'Bài trắc nghiệm',method:'Sáu câu hỏi tình huống gán điểm cho bốn nguyên tố.'},{slug:'chinese-zodiac',name:'Hoàng đạo Trung Hoa',description:'Khám phá con giáp và ngũ hành trong vòng tuần hoàn phương Đông.',category:'Ngày sinh & vũ trụ',color:'#ED9D8E',minutes:2,input:'Ngày sinh',method:'Dùng lịch Trung Hoa của trình duyệt để xét ranh giới Tết.'},{slug:'spirit-animal',name:'Linh vật đại diện',description:'Gặp một người bạn biểu tượng đồng điệu với bản năng của bạn.',category:'Tính cách & bản sắc',color:'#8CCBB1',minutes:3,input:'Bài trắc nghiệm',method:'Sáu câu hỏi gán điểm cho bốn linh vật.'},{slug:'fantasy-archetype',name:'Nhân vật giả tưởng',description:'Nếu cuộc đời là một câu chuyện, bạn sẽ bước vào vai trò nào?',category:'Tính cách & bản sắc',color:'#E3BD86',minutes:4,input:'Bài trắc nghiệm',method:'Sáu câu hỏi gán điểm cho tám archetype.'}];
function userFrom(request:Request):User|null{const id=request.headers.get('oai-authenticated-user-id');if(!id)return null;const email=request.headers.get('oai-authenticated-user-email')||'';const encoded=request.headers.get('oai-authenticated-user-full-name');const name=encoded&&request.headers.get('oai-authenticated-user-full-name-encoding')==='percent-encoded-utf-8'?decodeURIComponent(encoded):email;return {id,email,name};}
function isAdmin(user:User,env:Env){const configured=env.ADMIN_USER_IDS?.split(',').map(x=>x.trim()).filter(Boolean)||[];return configured.includes(user.id)||configured.includes(user.email);}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});}
async function body(request:Request){try{return await request.json() as Record<string,unknown>}catch{return null;}}
function dbOrFail(env:Env){if(!env.DB)throw new Error('D1 binding DB chưa được cấu hình.');return env.DB;}
async function ensureUser(db:D1Database,user:User){await db.prepare('INSERT INTO users (id,email,name,updated_at) VALUES (?1,?2,?3,?4) ON CONFLICT(id) DO UPDATE SET email=excluded.email,name=excluded.name,updated_at=excluded.updated_at').bind(user.id,user.email,user.name,new Date().toISOString()).run();}
const articleSelect='SELECT articles.id,articles.slug,articles.title,articles.excerpt,articles.content,articles.category,articles.status,articles.created_at,articles.updated_at,users.name AS author_name,articles.author_id FROM articles JOIN users ON users.id=articles.author_id';
function articleJson(row:any,userId:string){return {id:row.id,slug:row.slug,title:row.title,excerpt:row.excerpt,content:row.content,category:row.category,status:row.status,createdAt:row.created_at,updatedAt:row.updated_at,authorName:row.author_name||'Người viết',editable:row.author_id===userId};}
function cleanArticle(value:Record<string,unknown>|null){if(!value||typeof value.title!=='string'||typeof value.excerpt!=='string'||typeof value.content!=='string'||typeof value.category!=='string'||!['draft','published'].includes(String(value.status)))return null;const cleaned={title:value.title.trim().slice(0,120),excerpt:value.excerpt.trim().slice(0,240),content:value.content.trim().slice(0,30000),category:value.category.trim().slice(0,50),status:value.status as 'draft'|'published'};return cleaned.title.length>=3&&cleaned.excerpt.length>=10&&cleaned.content.length>=20&&cleaned.category.length>=2?cleaned:null;}
async function api(request:Request,env:Env){const url=new URL(request.url);const user=userFrom(request);if(url.pathname==='/api/me')return json(user?{authenticated:true,...user,isAdmin:isAdmin(user,env)}:{authenticated:false});if(!user)return json({error:'Vui lòng đăng nhập để đồng bộ dữ liệu.'},401);const db=dbOrFail(env);await ensureUser(db,user);
 if(url.pathname==='/api/articles'&&request.method==='GET'){const mine=url.searchParams.get('mine')==='1';const rows=mine?await db.prepare(`${articleSelect} WHERE articles.author_id=?1 ORDER BY articles.updated_at DESC`).bind(user.id).all():await db.prepare(`${articleSelect} WHERE articles.status='published' OR articles.author_id=?1 ORDER BY articles.updated_at DESC`).bind(user.id).all();return json(rows.results.map(row=>articleJson(row,user.id)));}
 const articleMatch=url.pathname.match(/^\/api\/articles\/([^/]+)$/);
 if(articleMatch&&request.method==='GET'){const row=await db.prepare(`${articleSelect} WHERE (articles.slug=?1 OR articles.id=?1) AND (articles.status='published' OR articles.author_id=?2)`).bind(articleMatch[1],user.id).first<any>();return row?json(articleJson(row,user.id)):json({error:'Không tìm thấy bài viết.'},404);}
 if(url.pathname==='/api/articles'&&request.method==='POST'){const value=cleanArticle(await body(request));if(!value)return json({error:'Tiêu đề, tóm tắt hoặc nội dung bài viết chưa hợp lệ.'},400);const id=crypto.randomUUID(),now=new Date().toISOString(),base=value.title.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/gi,'d').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,72)||'bai-viet',slug=`${base}-${id.slice(0,8)}`;await db.prepare('INSERT INTO articles (id,author_id,slug,title,excerpt,content,category,status,created_at,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10)').bind(id,user.id,slug,value.title,value.excerpt,value.content,value.category,value.status,now,now).run();return json({id,slug,...value,createdAt:now,updatedAt:now,authorName:user.name||user.email||'Người viết',editable:true},201);}
 if(articleMatch&&request.method==='PUT'){const existing=await db.prepare('SELECT id FROM articles WHERE id=?1 AND author_id=?2').bind(articleMatch[1],user.id).first();if(!existing)return json({error:'Bạn không có quyền sửa bài viết này.'},403);const value=cleanArticle(await body(request));if(!value)return json({error:'Tiêu đề, tóm tắt hoặc nội dung bài viết chưa hợp lệ.'},400);const now=new Date().toISOString();await db.prepare('UPDATE articles SET title=?1,excerpt=?2,content=?3,category=?4,status=?5,updated_at=?6 WHERE id=?7 AND author_id=?8').bind(value.title,value.excerpt,value.content,value.category,value.status,now,articleMatch[1],user.id).run();const row=await db.prepare(`${articleSelect} WHERE articles.id=?1`).bind(articleMatch[1]).first<any>();return json(articleJson(row,user.id));}
 if(url.pathname==='/api/readings'&&request.method==='GET'){const rows=await db.prepare('SELECT id,tool_slug,created_at,input_summary,result_json,saved,added_to_profile FROM readings WHERE user_id=?1 ORDER BY created_at DESC').bind(user.id).all();return json(rows.results.map((r:any)=>({id:r.id,toolSlug:r.tool_slug,createdAt:r.created_at,inputSummary:r.input_summary,result:JSON.parse(r.result_json),saved:Boolean(r.saved),addedToProfile:Boolean(r.added_to_profile)})));}
 if(url.pathname==='/api/readings'&&request.method==='POST'){const value=await body(request);if(!value||typeof value.id!=='string'||typeof value.toolSlug!=='string'||typeof value.createdAt!=='string'||typeof value.inputSummary!=='string'||!value.result||typeof value.result!=='object')return json({error:'Dữ liệu kết quả không hợp lệ.'},400);const r=value.result as Record<string,unknown>;if(typeof r.title!=='string'||typeof r.details!=='string'||!Array.isArray(r.traits)||!Array.isArray(r.facts))return json({error:'Thiếu nội dung kết quả.'},400);await db.prepare('INSERT INTO readings (id,user_id,tool_slug,created_at,input_summary,result_json,saved,added_to_profile) VALUES (?1,?2,?3,?4,?5,?6,?7,?8) ON CONFLICT(id) DO UPDATE SET result_json=excluded.result_json,saved=excluded.saved,added_to_profile=excluded.added_to_profile WHERE readings.user_id=excluded.user_id').bind(value.id,user.id,value.toolSlug,value.createdAt,value.inputSummary,JSON.stringify(r),Boolean(value.saved)?1:0,Boolean(value.addedToProfile)?1:0).run();return json({ok:true,id:value.id},201);}
 const match=url.pathname.match(/^\/api\/readings\/([^/]+)$/);if(match&&request.method==='PATCH'){const value=await body(request);if(!value||typeof value!=='object')return json({error:'Dữ liệu cập nhật không hợp lệ.'},400);const columns:string[]=[];const values:unknown[]=[];if(typeof value.saved==='boolean'){columns.push('saved=?');values.push(value.saved?1:0);}if(typeof value.addedToProfile==='boolean'){columns.push('added_to_profile=?');values.push(value.addedToProfile?1:0);}if(!columns.length)return json({error:'Không có thay đổi.'},400);values.push(match[1],user.id);await db.prepare(`UPDATE readings SET ${columns.join(',')} WHERE id=? AND user_id=?`).bind(...values).run();return json({ok:true});}
 if(match&&request.method==='DELETE'){await db.prepare('DELETE FROM readings WHERE id=?1 AND user_id=?2').bind(match[1],user.id).run();return json({ok:true});}
 if(url.pathname==='/api/readings'&&request.method==='DELETE'){await db.prepare('DELETE FROM readings WHERE user_id=?1').bind(user.id).run();return json({ok:true});}
 if((url.pathname==='/api/admin/content'||url.pathname==='/api/content')&&request.method==='GET'){if(url.pathname==='/api/admin/content'&&!isAdmin(user,env))return json({error:'Bạn không có quyền quản trị.'},403);const rows=await db.prepare('SELECT slug,name,description,category,color,minutes,input,method,updated_at FROM content ORDER BY slug').bind().all();return json(defaults.map(tool=>({...tool,...rows.results.find((row:any)=>row.slug===tool.slug)})));}
 const contentMatch=url.pathname.match(/^\/api\/admin\/content\/([a-z0-9-]+)$/);if(contentMatch&&request.method==='PUT'){if(!isAdmin(user,env))return json({error:'Bạn không có quyền quản trị.'},403);const value=await body(request);if(!value||typeof value.name!=='string'||typeof value.description!=='string'||typeof value.category!=='string'||typeof value.color!=='string'||typeof value.method!=='string'||!Number.isFinite(Number(value.minutes))||typeof value.input!=='string')return json({error:'Nội dung công cụ chưa đủ trường.'},400);await db.prepare('INSERT INTO content (slug,name,description,category,color,minutes,input,method,updated_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9) ON CONFLICT(slug) DO UPDATE SET name=excluded.name,description=excluded.description,category=excluded.category,color=excluded.color,minutes=excluded.minutes,input=excluded.input,method=excluded.method,updated_at=excluded.updated_at').bind(contentMatch[1],value.name,value.description,value.category,value.color,Number(value.minutes),value.input,value.method,new Date().toISOString()).run();return json({ok:true});}
 if(url.pathname==='/api/admin/overview'&&request.method==='GET'){if(!isAdmin(user,env))return json({error:'Bạn không có quyền quản trị.'},403);const counts=await db.prepare('SELECT COUNT(*) AS readings, COUNT(DISTINCT user_id) AS users FROM readings').bind().first<any>();return json({readings:Number(counts?.readings||0),users:Number(counts?.users||0)});}
 return json({error:'API không tồn tại.'},404);}
export default {async fetch(request:Request,env:Env){const url=new URL(request.url);if(url.pathname.startsWith('/api/')){try{return await api(request,env);}catch(error){return json({error:error instanceof Error?error.message:'Máy chủ chưa sẵn sàng.'},503);}}if(env.ASSETS){const asset=await env.ASSETS.fetch(request);if(asset.status!==404)return asset;return env.ASSETS.fetch(new Request(new URL('/index.html',request.url),request));}return new Response('Assets unavailable',{status:503});}};
