import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/CocCoc/Browser/Application/browser.exe',headless:true});
const root='http://localhost:4174/mystical-self/#';
try {const page=await browser.newPage({viewport:{width:390,height:844},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(root+'/codex');await page.locator('.codex-index-entry').first().waitFor();assert.equal(await page.locator('.codex-index-entry').count(),41);const routes=await page.locator('.codex-index-entry').evaluateAll(es=>es.map(e=>e.getAttribute('href')));for(const route of routes){await page.goto('http://localhost:4174/mystical-self/'+route);await page.locator('.codex-guide summary').waitFor();await page.locator('.codex-guide summary').click();assert.ok(await page.locator('.codex-guide dt').count()===3);assert.ok(await page.locator('.explore-next a').count()>0);}
 await page.goto(root+'/codex');await page.getByLabel('Tìm trong Cosmic Codex').fill('zzzz-not-found');await page.getByRole('heading',{name:'Chưa tìm thấy đường nối này.'}).waitFor();await page.getByRole('button',{name:'Xem toàn bộ Codex'}).click();await page.locator('.codex-index-entry').first().waitFor();assert.equal(await page.locator('.codex-index-entry').count(),41);await page.goto(root+'/codex/not-real');await page.getByRole('heading',{name:'Chưa tìm thấy mục này.'}).waitFor();
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await page.goto(root+'/codex/zodiac-scorpio');await page.locator('.codex-guide').waitFor();assert.ok(await page.locator('body').evaluate(e=>e.scrollWidth<=innerWidth),`overflow ${width}`);}
 await page.setViewportSize({width:390,height:844});assert.equal(await page.locator('.bottom-nav a[href="#/codex"]').getAttribute('aria-current'),'page');await page.locator('.codex-guide summary').focus();await page.keyboard.press('Enter');assert.equal(await page.locator('.codex-guide').getAttribute('open'),'');await page.locator('.codex-guide').screenshot({path:'codex-completion-mobile.png'});
 await page.goto(root+'/');await page.locator('#zodiac').waitFor();await page.locator('.cosmic-nav a[href="#zodiac"]').click();assert.equal(new URL(page.url()).hash,'#/');await page.locator('.skip-link').focus();await page.keyboard.press('Enter');assert.equal(new URL(page.url()).hash,'#/');assert.ok(await page.locator('#main').evaluate(e=>e===document.activeElement));
 await page.locator('#houses .house-point').first().click();for(let i=0;i<6;i++){await page.locator('#houses .house-point').nth(i).click();await page.locator('.house-axis button').click();assert.equal(await page.locator('#houses .house-point').nth(i+6).getAttribute('aria-pressed'),'true');}
 await page.goto(root+'/codex/zodiac-scorpio');await page.getByRole('link',{name:'Trở về Explorer ↗'}).click();await page.locator('#zodiac .zodiac-point[aria-pressed=true]').waitFor();assert.equal(await page.locator('#zodiac .zodiac-point[aria-pressed=true]').getAttribute('aria-label'),'Bọ Cạp');
 await page.locator('#houses .house-groups summary').click();assert.equal(await page.locator('.house-groups button').count(),12);await page.locator('.house-groups button').last().click();assert.equal(await page.locator('#houses .house-point').last().getAttribute('aria-pressed'),'true');
 assert.deepEqual(errors,[]);console.log('PASS: all 41 Codex entities/guides/onward links, empty/invalid states, 4 widths, mobile nav, keyboard guide, hash-safe anchors, six house axes.');
}finally{await browser.close();}
