import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/CocCoc/Browser/Application/browser.exe',headless:true});
const url='http://localhost:4174/mystical-self/#/';
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);const section=page.locator('#houses');await section.scrollIntoViewIfNeeded();const buttons=section.locator('.house-point');assert.equal(await buttons.count(),12);
 for(let i=0;i<12;i++){await buttons.nth(i).click();assert.equal(await buttons.nth(i).getAttribute('aria-pressed'),'true');assert.match(await section.locator('.house-detail h3').innerText(),new RegExp('Nhà '+(i+1)+' ·'));assert.ok((await section.locator('.house-keywords').innerText()).length>5);assert.equal(await section.locator('.explore-next a').count(),1);}
 await buttons.first().focus();await page.keyboard.press('ArrowLeft');assert.equal(await buttons.nth(11).getAttribute('aria-pressed'),'true');await page.keyboard.press('Home');assert.equal(await buttons.first().getAttribute('aria-pressed'),'true');await page.keyboard.press('End');assert.equal(await buttons.nth(11).getAttribute('aria-pressed'),'true');await page.keyboard.press('ArrowRight');assert.equal(await buttons.first().getAttribute('aria-pressed'),'true');
 assert.match(await section.locator('.house-learning').innerText(),/WHAT[\s\S]*HOW[\s\S]*WHERE/);await buttons.nth(7).click();const onward=section.locator('.explore-next a');assert.match(await onward.innerText(),/Liên tưởng cung · hiện đại/);await onward.click();await page.waitForURL('**/codex/zodiac-scorpio');assert.ok(!(await page.locator('main').innerText()).includes('Chưa tìm thấy mục này'));await page.goto(url);
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await section.scrollIntoViewIfNeeded();assert.ok(await section.evaluate(e=>e.scrollWidth<=e.clientWidth),`overflow ${width}`);if(width<760){await section.locator('select').selectOption('7');assert.equal(await buttons.nth(7).getAttribute('aria-pressed'),'true');}}
 await page.setViewportSize({width:390,height:844});await section.screenshot({path:'house-wu04-mobile.png'});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});const mobile=await context.newPage();await mobile.goto(url);await mobile.locator('#houses').scrollIntoViewIfNeeded();await mobile.locator('#houses .house-point').nth(7).tap();assert.equal(await mobile.locator('#houses .house-point').nth(7).getAttribute('aria-pressed'),'true');assert.deepEqual(errors,[]);console.log('PASS: 12 houses/detail, keyboard, mobile selector/touch, four widths, beginner distinction and House VIII onward route.');
}finally{await browser.close();}
