import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/CocCoc/Browser/Application/browser.exe',headless:true});
const url='http://localhost:4174/mystical-self/#/';
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000},reducedMotion:'reduce'});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);
 const section=page.locator('#planets');await section.scrollIntoViewIfNeeded();const buttons=section.locator('.planet-orbit button');assert.equal(await buttons.count(),10);
 for(let i=0;i<10;i++) {await buttons.nth(i).click();await page.waitForTimeout(200);assert.equal(await buttons.nth(i).getAttribute('aria-pressed'),'true');assert.ok((await section.locator('.planet-identity h3').innerText()).length>2); for(const label of ['Thiên văn','Thần thoại','Chiêm tinh']) {await section.getByRole('button',{name:label,exact:true}).click();assert.ok((await section.locator('.planet-layer p').first().innerText()).length>15);} }
 await buttons.first().focus();await page.keyboard.press('ArrowRight');assert.equal(await buttons.nth(1).getAttribute('aria-pressed'),'true');await page.keyboard.press('End');assert.equal(await buttons.nth(9).getAttribute('aria-pressed'),'true');await page.keyboard.press('Home');assert.equal(await buttons.first().getAttribute('aria-pressed'),'true');await page.keyboard.press('ArrowLeft');assert.equal(await buttons.nth(9).getAttribute('aria-pressed'),'true');
 for(const [index,ids] of [[4,['zodiac-aries','zodiac-scorpio']],[9,['zodiac-scorpio']],[3,['zodiac-taurus','zodiac-libra']]]) {await buttons.nth(index).click();await page.waitForTimeout(200);for(const id of ids){const link=section.locator(`.planet-rulership a[href="#/codex/${id}"]`);assert.equal(await link.count(),1);await link.click();await page.waitForURL('**/codex/'+id);assert.ok(!(await page.locator('main').innerText()).includes('Chưa tìm thấy mục này'));await page.goto(url);await buttons.nth(index).click();await page.waitForTimeout(200);}}
 for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:1000});await section.scrollIntoViewIfNeeded();assert.ok(await section.evaluate(e=>e.scrollWidth<=e.clientWidth),`overflow ${width}`);await section.getByRole('button',{name:'Thiên thể tiếp theo',exact:true}).click();}
 await page.setViewportSize({width:390,height:844});await section.scrollIntoViewIfNeeded();await section.screenshot({path:'planet-wu03-mobile.png'});
 const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,reducedMotion:'reduce'});const mobile=await context.newPage();await mobile.goto(url);await mobile.locator('#planets').scrollIntoViewIfNeeded();await mobile.locator('#planets .planet-orbit button').nth(4).tap();assert.equal(await mobile.locator('#planets .planet-orbit button').nth(4).getAttribute('aria-pressed'),'true');await mobile.locator('#planets').getByRole('button',{name:'Thiên văn',exact:true}).tap();assert.match(await mobile.locator('#planets .planet-layer').innerText(),/THÔNG TIN KHOA HỌC/);
 assert.deepEqual(errors,[]);console.log('PASS: 10 bodies × 3 layers, keyboard wrap/Home/End, Mars/Pluto/Venus links, 4 viewport widths, touch selection and layers; no page errors.');
}finally{await browser.close();}
